== Déploiement Poste de Dev : Skaffold

[%step]
* A chaque modif. des sources
** Reconstruction  des images Docker 
** Déploiement/Mise à jour de l'application sur Kubernetes 
* [.blue]#Pas d'exigences de sécurité#

=== Mise en Place de Skaffold (cas classique)

[%step]
* Créer un Dockerfile "autonome"
** Le Dockerfile doit orchestrer les outils de build (npm, webpack, ...)
* Créer la config Skaffold

=== Configuration Skaffold (version classique)

[source, yaml]
----
apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: elkouhen/books-gui
deploy:
  helm:
    releases:
    - name: books-gui
      chartPath: ../app-charts/books-gui
      setValues:
        ingress.enabled: false
        h2.enabled: false
        service.type: LoadBalancer
      setValueTemplates:
        image.tag: "{{.DIGEST}}"
----

=== Mise en Place de Skaffold (cas Maven)

[%step]
* Configurer le plugin Maven jib-maven-plugin
** Le plugin génère un Dockerfile qui optimise la construction des images Docker pour les applications java
** La création d'un Dockerfile n'est pas nécessaire !
* Créer la config Skaffold
** Configurer jibMaven dans la config. Skaffold

=== Configuration Skaffold (version Maven)

[source, yaml]
----
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: elkouhen/books-api
    jibMaven: {}
deploy:
  helm:
    releases:
    - name: books-api-dev
      chartPath: ../app-charts/books-api
      overrides:
        auth:
          enabled: false
        h2:
          enabled: false
        ingress:
          enabled: false
----

=== Configuration de JIB

[source, xml]
----
<plugin>
   <groupId>com.google.cloud.tools</groupId>
   <artifactId>jib-maven-plugin</artifactId>
   <version>1.4.0</version>
   <configuration>
      <allowInsecureRegistries>true</allowInsecureRegistries>
      <container>
         <jvmFlags>
            <jvmFlag>-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005</jvmFlag>
            <jvmFlag>-Djava.security.egd=file:/dev/./urandom</jvmFlag>
         </jvmFlags>
         <ports>
            <port>8080</port>
            <port>5005</port>
         </ports>
      </container>
   </configuration>
</plugin>
----

=== Démarrage de Skaffold

[source, bash]
----
# skaffold dev -f skaffold-local.yaml
----

=== Démo

=== Test du back end

[source, bash]
----
[root@master1 ~]# kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
books-api    NodePort    10.109.185.27   <none>        80:31185/TCP   2m
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP        6m

[root@master1 ~]# curl http://10.109.185.27/api/books
[{"id":1,"title":"Design Pattern","author":"Erich Gamma, John Vlissides, Ralph E.. Johnson et Richard Helm"},\
{"id":2,"title":"Effective Java","author":"Joshua Bloch"},\
{"id":3,"title":"The C++ Programming Language","author":"Bjarne Stroustrup"},\
{"id":4,"title":"The Clean Coder: A Code of Conduct for Professional Programmers","author":"Robert C. Martin"}]
----
